server:
  port: 8080

spring:
  application:
    name: kelea-technical-test

  # Configuración de H2 para desarrollo
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  sql:
    init:
      mode: always
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

management:
  zipkin:
    tracing:
      export:
        enabled: false
  tracing:
    sampling:
      probability: 1.0
  opentelemetry:
    resource-attributes:
      service.name: kelea-technical-test
  endpoints:
    web:
      exposure:
        # Exponemos los endpoints de health, info y prometheus
        include: "health,info,prometheus"
  endpoint:
    health:
      # Mostramos siempre los detalles completos del estado de salud
      show-details: always

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
  level:
    dev.rodrigovaamonde: DEBUG
    org.springframework.web: DEBUG


